import { getChallengeSlugCandidates } from './challengeSlugAliases';

export type LocalChallenge = {
  id: number;
  chapter_id: number;
  order_index: number;
  slug: string;
  title: string;
  description: string;
  difficulty: string;
  tags: string[];
  xp_reward: number;
  time_limit_seconds: number;
  hints: string[];
  setup_script: string;
  validator_script: string;
};

export const fallbackChallenges: LocalChallenge[] = [
  // Chapter 1 — Awakening
  {
    id: 1001,
    chapter_id: 1,
    order_index: 1,
    slug: 'echo-hello',
    title: 'Hello Terminal',
    description: 'Write "hello world" into /tmp/hello.txt.',
    difficulty: 'E',
    tags: ['terminal', 'concept'],
    xp_reward: 30,
    time_limit_seconds: 60,
    hints: ['Use echo to print text.', 'Redirect output into a file.', 'echo "hello world" > /tmp/hello.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/hello.txt && grep -qx "hello world" /tmp/hello.txt && echo PASS || echo FAIL'
  },
  {
    id: 1002,
    chapter_id: 1,
    order_index: 2,
    slug: 'pwd-ls-cd',
    title: 'Where Am I',
    description: 'Save the absolute path of /tmp/arena into /tmp/arena/pwd.txt.',
    difficulty: 'E',
    tags: ['navigation', 'concept'],
    xp_reward: 35,
    time_limit_seconds: 90,
    hints: ['Change directory to /tmp/arena.', 'Run pwd and redirect.', 'pwd > /tmp/arena/pwd.txt'],
    setup_script: 'mkdir -p /tmp/arena',
    validator_script: 'test -f /tmp/arena/pwd.txt && grep -qx "/tmp/arena" /tmp/arena/pwd.txt && echo PASS || echo FAIL'
  },
  {
    id: 1003,
    chapter_id: 1,
    order_index: 3,
    slug: 'paths-01',
    title: 'Record the Listing',
    description: 'List files in /tmp/arena and save output to /tmp/arena/list.txt.',
    difficulty: 'E',
    tags: ['terminal', 'concept'],
    xp_reward: 35,
    time_limit_seconds: 90,
    hints: ['Create a listing file with ls.', 'ls /tmp/arena > /tmp/arena/list.txt'],
    setup_script: 'mkdir -p /tmp/arena && touch /tmp/arena/a.txt /tmp/arena/b.txt',
    validator_script: 'test -f /tmp/arena/list.txt && grep -q "a.txt" /tmp/arena/list.txt && grep -q "b.txt" /tmp/arena/list.txt && echo PASS || echo FAIL'
  },
  {
    id: 1004,
    chapter_id: 1,
    order_index: 4,
    slug: 'help-01',
    title: 'Seek Help',
    description: 'Save the help output of ls into /tmp/ls-help.txt.',
    difficulty: 'E',
    tags: ['manpage', 'concept'],
    xp_reward: 40,
    time_limit_seconds: 120,
    hints: ['Use ls --help.', 'Redirect the output to /tmp/ls-help.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/ls-help.txt && grep -q "Usage" /tmp/ls-help.txt && echo PASS || echo FAIL'
  },

  // Chapter 2 — First Steps
  {
    id: 1005,
    chapter_id: 2,
    order_index: 1,
    slug: 'touch-01',
    title: 'Create a File',
    description: 'Create /tmp/files/report.txt.',
    difficulty: 'E',
    tags: ['files', 'touch'],
    xp_reward: 40,
    time_limit_seconds: 90,
    hints: ['Use touch to create a file.', 'touch /tmp/files/report.txt'],
    setup_script: 'mkdir -p /tmp/files',
    validator_script: 'test -f /tmp/files/report.txt && echo PASS || echo FAIL'
  },
  {
    id: 1006,
    chapter_id: 2,
    order_index: 2,
    slug: 'mkdir-01',
    title: 'Build the Tree',
    description: 'Create /tmp/projects/app/logs using mkdir -p.',
    difficulty: 'E',
    tags: ['mkdir', 'files'],
    xp_reward: 40,
    time_limit_seconds: 90,
    hints: ['Use mkdir -p to build nested folders.', 'mkdir -p /tmp/projects/app/logs'],
    setup_script: 'true',
    validator_script: 'test -d /tmp/projects/app/logs && echo PASS || echo FAIL'
  },
  {
    id: 1007,
    chapter_id: 2,
    order_index: 3,
    slug: 'cp-01',
    title: 'Copy the Brief',
    description: 'Copy /tmp/src.txt to /tmp/copy.txt.',
    difficulty: 'E',
    tags: ['cp', 'files'],
    xp_reward: 45,
    time_limit_seconds: 90,
    hints: ['Use cp to copy files.', 'cp /tmp/src.txt /tmp/copy.txt'],
    setup_script: 'echo "intel" > /tmp/src.txt',
    validator_script: 'test -f /tmp/copy.txt && diff -q /tmp/src.txt /tmp/copy.txt >/dev/null && echo PASS || echo FAIL'
  },
  {
    id: 1008,
    chapter_id: 2,
    order_index: 4,
    slug: 'mv-01',
    title: 'Rename the File',
    description: 'Move /tmp/old.txt to /tmp/new.txt.',
    difficulty: 'E',
    tags: ['mv', 'files'],
    xp_reward: 45,
    time_limit_seconds: 90,
    hints: ['Use mv to rename.', 'mv /tmp/old.txt /tmp/new.txt'],
    setup_script: 'echo "rename" > /tmp/old.txt',
    validator_script: 'test -f /tmp/new.txt && ! test -f /tmp/old.txt && echo PASS || echo FAIL'
  },

  // Chapter 3 — Reading the World
  {
    id: 1009,
    chapter_id: 3,
    order_index: 1,
    slug: 'grep-01',
    title: 'Find Errors',
    description: 'Extract lines containing "error" from /tmp/log.txt into /tmp/errors.txt.',
    difficulty: 'D',
    tags: ['grep', 'text'],
    xp_reward: 55,
    time_limit_seconds: 120,
    hints: ['Use grep to filter lines.', 'grep "error" /tmp/log.txt > /tmp/errors.txt'],
    setup_script: 'printf "ok\nerror: bad\nok\nerror: fail\n" > /tmp/log.txt',
    validator_script: 'test -f /tmp/errors.txt && grep -q "error:" /tmp/errors.txt && ! grep -q "^ok" /tmp/errors.txt && echo PASS || echo FAIL'
  },
  {
    id: 1010,
    chapter_id: 3,
    order_index: 2,
    slug: 'grep-flags',
    title: 'Count Lines',
    description: 'Write the line count of /tmp/data.txt to /tmp/lines.txt.',
    difficulty: 'D',
    tags: ['wc', 'text'],
    xp_reward: 55,
    time_limit_seconds: 120,
    hints: ['Use wc -l.', 'wc -l /tmp/data.txt > /tmp/lines.txt'],
    setup_script: 'printf "a\nb\nc\nd\ne\n" > /tmp/data.txt',
    validator_script: 'test -f /tmp/lines.txt && grep -q "5" /tmp/lines.txt && echo PASS || echo FAIL'
  },
  {
    id: 1011,
    chapter_id: 3,
    order_index: 3,
    slug: 'wc-01',
    title: 'Sort the List',
    description: 'Sort /tmp/numbers.txt numerically and save to /tmp/sorted.txt.',
    difficulty: 'D',
    tags: ['sort', 'text'],
    xp_reward: 55,
    time_limit_seconds: 120,
    hints: ['Use sort -n.', 'sort -n /tmp/numbers.txt > /tmp/sorted.txt'],
    setup_script: 'printf "42\n3\n17\n8\n" > /tmp/numbers.txt',
    validator_script: 'test -f /tmp/sorted.txt && head -n1 /tmp/sorted.txt | grep -qx "3" && echo PASS || echo FAIL'
  },
  {
    id: 1012,
    chapter_id: 3,
    order_index: 4,
    slug: 'sort-01',
    title: 'Cut Columns',
    description: 'Extract the second column from /tmp/people.csv into /tmp/names.txt.',
    difficulty: 'D',
    tags: ['cut', 'text'],
    xp_reward: 60,
    time_limit_seconds: 120,
    hints: ['Use cut -d , -f2.', 'cut -d \",\" -f2 /tmp/people.csv > /tmp/names.txt'],
    setup_script: 'printf "1,Ana\n2,Ben\n3,Cy\n" > /tmp/people.csv',
    validator_script: 'test -f /tmp/names.txt && grep -qx "Ana" /tmp/names.txt && echo PASS || echo FAIL'
  },

  // Chapter 4 — Power of Pipes
  {
    id: 1013,
    chapter_id: 4,
    order_index: 1,
    slug: 'pipe-01',
    title: 'Pipe the Names',
    description: 'Filter names containing "ana" from /tmp/names.txt into /tmp/ana.txt.',
    difficulty: 'D',
    tags: ['pipes', 'grep'],
    xp_reward: 60,
    time_limit_seconds: 120,
    hints: ['Use cat | grep.', 'cat /tmp/names.txt | grep -i ana > /tmp/ana.txt'],
    setup_script: 'printf "Ana\nBob\nAnastasia\nEve\n" > /tmp/names.txt',
    validator_script: 'test -f /tmp/ana.txt && grep -qi "ana" /tmp/ana.txt && ! grep -qi "bob" /tmp/ana.txt && echo PASS || echo FAIL'
  },
  {
    id: 1014,
    chapter_id: 4,
    order_index: 2,
    slug: 'redir-01',
    title: 'Append the Log',
    description: 'Append "beta" to /tmp/append.txt.',
    difficulty: 'D',
    tags: ['redirect', 'files'],
    xp_reward: 60,
    time_limit_seconds: 120,
    hints: ['Use >> to append.', 'echo beta >> /tmp/append.txt'],
    setup_script: 'echo "alpha" > /tmp/append.txt',
    validator_script: 'grep -q "alpha" /tmp/append.txt && grep -q "beta" /tmp/append.txt && echo PASS || echo FAIL'
  },
  {
    id: 1015,
    chapter_id: 4,
    order_index: 3,
    slug: 'stderr-01',
    title: 'Tee the Signal',
    description: 'Write "system" into /tmp/tee.txt using tee.',
    difficulty: 'D',
    tags: ['tee', 'pipes'],
    xp_reward: 65,
    time_limit_seconds: 120,
    hints: ['Use tee to write output to a file.', 'echo "system" | tee /tmp/tee.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/tee.txt && grep -qx "system" /tmp/tee.txt && echo PASS || echo FAIL'
  },
  {
    id: 1016,
    chapter_id: 4,
    order_index: 4,
    slug: 'tee-01',
    title: 'Xargs Builder',
    description: 'Create /tmp/x1 /tmp/x2 /tmp/x3 using xargs on /tmp/nums.txt.',
    difficulty: 'D',
    tags: ['xargs', 'pipes'],
    xp_reward: 65,
    time_limit_seconds: 120,
    hints: ['Use xargs -n1.', 'cat /tmp/nums.txt | xargs -n1 -I{} touch /tmp/x{}'],
    setup_script: 'printf "1\n2\n3\n" > /tmp/nums.txt',
    validator_script: 'test -f /tmp/x1 && test -f /tmp/x2 && test -f /tmp/x3 && echo PASS || echo FAIL'
  },

  // Chapter 5 — Hidden Knowledge
  {
    id: 1017,
    chapter_id: 5,
    order_index: 1,
    slug: 'perm-strings',
    title: 'Lock it down',
    description: 'Set /tmp/secret.txt to 600.',
    difficulty: 'D',
    tags: ['permissions', 'chmod'],
    xp_reward: 75,
    time_limit_seconds: 120,
    hints: ['Owner read/write only.', 'Try chmod 600 /tmp/secret.txt.'],
    setup_script: 'echo secret > /tmp/secret.txt && chmod 777 /tmp/secret.txt',
    validator_script: 'perms=$(stat -c "%a" /tmp/secret.txt); [ "$perms" = "600" ] && echo PASS || echo FAIL'
  },
  {
    id: 1018,
    chapter_id: 5,
    order_index: 2,
    slug: 'chmod-01',
    title: 'Make it Executable',
    description: 'Set /tmp/script.sh to 755.',
    difficulty: 'D',
    tags: ['permissions', 'chmod'],
    xp_reward: 70,
    time_limit_seconds: 120,
    hints: ['Use chmod 755.', 'chmod 755 /tmp/script.sh'],
    setup_script: 'echo "echo ok" > /tmp/script.sh && chmod 600 /tmp/script.sh',
    validator_script: 'perms=$(stat -c "%a" /tmp/script.sh); [ "$perms" = "755" ] && echo PASS || echo FAIL'
  },
  {
    id: 1019,
    chapter_id: 5,
    order_index: 3,
    slug: 'chmod-symbolic',
    title: 'Symbolic Power',
    description: 'Add execute permission for user on /tmp/run.sh (symbolic).',
    difficulty: 'D',
    tags: ['permissions', 'chmod'],
    xp_reward: 70,
    time_limit_seconds: 120,
    hints: ['Use chmod u+x.', 'chmod u+x /tmp/run.sh'],
    setup_script: 'echo "echo run" > /tmp/run.sh && chmod 600 /tmp/run.sh',
    validator_script: 'test -x /tmp/run.sh && echo PASS || echo FAIL'
  },
  {
    id: 1020,
    chapter_id: 5,
    order_index: 4,
    slug: 'chown-01',
    title: 'Sticky Share',
    description: 'Set /tmp/share to 1777.',
    difficulty: 'D',
    tags: ['permissions', 'chmod'],
    xp_reward: 80,
    time_limit_seconds: 120,
    hints: ['Sticky bit is 1 in front.', 'chmod 1777 /tmp/share'],
    setup_script: 'mkdir -p /tmp/share && chmod 755 /tmp/share',
    validator_script: 'perms=$(stat -c "%a" /tmp/share); [ "$perms" = "1777" ] && echo PASS || echo FAIL'
  },

  // Chapter 6 — Finding the Path
  {
    id: 1021,
    chapter_id: 6,
    order_index: 1,
    slug: 'find-name',
    title: 'Find by Name',
    description: 'Find *.log files in /tmp/findlab and save to /tmp/find.txt.',
    difficulty: 'C',
    tags: ['find', 'search'],
    xp_reward: 80,
    time_limit_seconds: 150,
    hints: ['Use find with -name "*.log".', 'find /tmp/findlab -name "*.log" > /tmp/find.txt'],
    setup_script: 'mkdir -p /tmp/findlab && touch /tmp/findlab/a.log /tmp/findlab/b.txt',
    validator_script: 'test -f /tmp/find.txt && grep -q ".log" /tmp/find.txt && echo PASS || echo FAIL'
  },
  {
    id: 1022,
    chapter_id: 6,
    order_index: 2,
    slug: 'find-type',
    title: 'Find Directories',
    description: 'List directories in /tmp/findlab and save to /tmp/dirs.txt.',
    difficulty: 'C',
    tags: ['find', 'search'],
    xp_reward: 80,
    time_limit_seconds: 150,
    hints: ['Use -type d.', 'find /tmp/findlab -type d > /tmp/dirs.txt'],
    setup_script: 'mkdir -p /tmp/findlab/alpha /tmp/findlab/beta',
    validator_script: 'test -f /tmp/dirs.txt && grep -q "/tmp/findlab/alpha" /tmp/dirs.txt && echo PASS || echo FAIL'
  },
  {
    id: 1023,
    chapter_id: 6,
    order_index: 3,
    slug: 'find-size',
    title: 'Find Large Files',
    description: 'Find files larger than 1KB in /tmp/findlab and save to /tmp/large.txt.',
    difficulty: 'C',
    tags: ['find', 'search'],
    xp_reward: 85,
    time_limit_seconds: 150,
    hints: ['Use -size +1k.', 'find /tmp/findlab -size +1k > /tmp/large.txt'],
    setup_script: 'mkdir -p /tmp/findlab && dd if=/dev/zero of=/tmp/findlab/big.bin bs=1024 count=2 >/dev/null 2>&1',
    validator_script: 'test -f /tmp/large.txt && grep -q "big.bin" /tmp/large.txt && echo PASS || echo FAIL'
  },
  {
    id: 1024,
    chapter_id: 6,
    order_index: 4,
    slug: 'find-mtime',
    title: 'Find Old Files',
    description: 'Find files older than 1 day in /tmp/findlab and save to /tmp/old.txt.',
    difficulty: 'C',
    tags: ['find', 'search'],
    xp_reward: 85,
    time_limit_seconds: 150,
    hints: ['Use -mtime +1.', 'find /tmp/findlab -mtime +1 > /tmp/old.txt'],
    setup_script: 'mkdir -p /tmp/findlab && touch -d "2 days ago" /tmp/findlab/old.log',
    validator_script: 'test -f /tmp/old.txt && grep -q "old.log" /tmp/old.txt && echo PASS || echo FAIL'
  },

  // Chapter 7 — The Architect
  {
    id: 1025,
    chapter_id: 7,
    order_index: 1,
    slug: 'sed-sub',
    title: 'Sed Replace',
    description: 'Replace "alpha" with "omega" in /tmp/sed.txt and save to /tmp/sed-out.txt.',
    difficulty: 'C',
    tags: ['sed', 'text'],
    xp_reward: 90,
    time_limit_seconds: 150,
    hints: ['Use sed s/alpha/omega/g.', 'sed "s/alpha/omega/g" /tmp/sed.txt > /tmp/sed-out.txt'],
    setup_script: 'echo "alpha alpha" > /tmp/sed.txt',
    validator_script: 'test -f /tmp/sed-out.txt && grep -q "omega" /tmp/sed-out.txt && echo PASS || echo FAIL'
  },
  {
    id: 1026,
    chapter_id: 7,
    order_index: 2,
    slug: 'sed-lines',
    title: 'Sed Delete',
    description: 'Remove lines starting with # from /tmp/conf.txt and save to /tmp/conf-clean.txt.',
    difficulty: 'C',
    tags: ['sed', 'text'],
    xp_reward: 90,
    time_limit_seconds: 150,
    hints: ['Use sed to delete lines.', 'sed "/^#/d" /tmp/conf.txt > /tmp/conf-clean.txt'],
    setup_script: 'printf "#note\nalpha\n#skip\nbeta\n" > /tmp/conf.txt',
    validator_script: 'test -f /tmp/conf-clean.txt && ! grep -q "^#" /tmp/conf-clean.txt && echo PASS || echo FAIL'
  },
  {
    id: 1027,
    chapter_id: 7,
    order_index: 3,
    slug: 'awk-cols',
    title: 'Awk Columns',
    description: 'Print the second column from /tmp/awk.txt into /tmp/awk-out.txt.',
    difficulty: 'C',
    tags: ['awk', 'text'],
    xp_reward: 95,
    time_limit_seconds: 150,
    hints: ['Use awk \'{print $2}\'', 'awk \'{print $2}\' /tmp/awk.txt > /tmp/awk-out.txt'],
    setup_script: 'printf "one two\nthree four\n" > /tmp/awk.txt',
    validator_script: 'test -f /tmp/awk-out.txt && grep -qx "two" /tmp/awk-out.txt && echo PASS || echo FAIL'
  },
  {
    id: 1028,
    chapter_id: 7,
    order_index: 4,
    slug: 'awk-filter',
    title: 'Awk Sum',
    description: 'Sum numbers in /tmp/nums.txt and write the total to /tmp/sum.txt.',
    difficulty: 'C',
    tags: ['awk', 'text'],
    xp_reward: 95,
    time_limit_seconds: 150,
    hints: ['Use awk to sum fields.', 'awk \'{s+=$1} END {print s}\' /tmp/nums.txt > /tmp/sum.txt'],
    setup_script: 'printf "2\n3\n5\n" > /tmp/nums.txt',
    validator_script: 'test -f /tmp/sum.txt && grep -qx "10" /tmp/sum.txt && echo PASS || echo FAIL'
  },

  // Chapter 8 — Process Hunter
  {
    id: 1029,
    chapter_id: 8,
    order_index: 1,
    slug: 'ps-01',
    title: 'Process List',
    description: 'Save ps aux output to /tmp/ps.txt.',
    difficulty: 'C',
    tags: ['process', 'ps'],
    xp_reward: 100,
    time_limit_seconds: 150,
    hints: ['Use ps aux.', 'ps aux > /tmp/ps.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/ps.txt && grep -q "PID" /tmp/ps.txt && echo PASS || echo FAIL'
  },
  {
    id: 1030,
    chapter_id: 8,
    order_index: 2,
    slug: 'pgrep-01',
    title: 'Stop the Sleeper',
    description: 'Kill the sleep process listed in /tmp/sleep.pid.',
    difficulty: 'C',
    tags: ['process', 'kill'],
    xp_reward: 110,
    time_limit_seconds: 150,
    hints: ['Use kill with the PID.', 'kill $(cat /tmp/sleep.pid)'],
    setup_script: 'sleep 300 & echo $! > /tmp/sleep.pid',
    validator_script: 'pid=$(cat /tmp/sleep.pid); kill -0 "$pid" 2>/dev/null && echo FAIL || echo PASS'
  },
  {
    id: 1031,
    chapter_id: 8,
    order_index: 3,
    slug: 'kill-01',
    title: 'Find the Target',
    description: 'Find the PID of sleep and save it to /tmp/pgrep.txt.',
    difficulty: 'C',
    tags: ['process', 'pgrep'],
    xp_reward: 110,
    time_limit_seconds: 150,
    hints: ['Use pgrep sleep.', 'pgrep sleep > /tmp/pgrep.txt'],
    setup_script: 'sleep 300 &',
    validator_script: 'test -f /tmp/pgrep.txt && grep -q "[0-9]" /tmp/pgrep.txt && echo PASS || echo FAIL'
  },
  {
    id: 1032,
    chapter_id: 8,
    order_index: 4,
    slug: 'jobs-01',
    title: 'Killall',
    description: 'Terminate all sleep processes.',
    difficulty: 'C',
    tags: ['process', 'killall'],
    xp_reward: 115,
    time_limit_seconds: 150,
    hints: ['Use killall sleep.'],
    setup_script: 'sleep 300 & sleep 300 &',
    validator_script: 'pgrep sleep >/dev/null 2>&1 && echo FAIL || echo PASS'
  },

  // Chapter 9 — Network Scout
  {
    id: 1033,
    chapter_id: 9,
    order_index: 1,
    slug: 'ping-01',
    title: 'Ping Localhost',
    description: 'Ping 127.0.0.1 once and save output to /tmp/ping.txt.',
    difficulty: 'B',
    tags: ['network', 'ping'],
    xp_reward: 120,
    time_limit_seconds: 150,
    hints: ['Use ping -c 1 127.0.0.1 > /tmp/ping.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/ping.txt && grep -q "1 packets transmitted" /tmp/ping.txt && echo PASS || echo FAIL'
  },
  {
    id: 1034,
    chapter_id: 9,
    order_index: 2,
    slug: 'ip-addr',
    title: 'Interface Check',
    description: 'Save ip addr output to /tmp/ip.txt.',
    difficulty: 'B',
    tags: ['network', 'ip'],
    xp_reward: 120,
    time_limit_seconds: 150,
    hints: ['Use ip addr > /tmp/ip.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/ip.txt && grep -q "inet" /tmp/ip.txt && echo PASS || echo FAIL'
  },
  {
    id: 1035,
    chapter_id: 9,
    order_index: 3,
    slug: 'ss-01',
    title: 'Open Ports',
    description: 'Save ss -tuln output to /tmp/ports.txt.',
    difficulty: 'B',
    tags: ['network', 'ss'],
    xp_reward: 125,
    time_limit_seconds: 150,
    hints: ['Use ss -tuln > /tmp/ports.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/ports.txt && grep -q "LISTEN" /tmp/ports.txt && echo PASS || echo FAIL'
  },
  {
    id: 1036,
    chapter_id: 9,
    order_index: 4,
    slug: 'curl-01',
    title: 'Curl Local File',
    description: 'Use curl to copy /tmp/web.txt into /tmp/curl.txt.',
    difficulty: 'B',
    tags: ['network', 'curl'],
    xp_reward: 125,
    time_limit_seconds: 150,
    hints: ['Use curl file:///tmp/web.txt > /tmp/curl.txt'],
    setup_script: 'echo "webdata" > /tmp/web.txt',
    validator_script: 'test -f /tmp/curl.txt && grep -qx "webdata" /tmp/curl.txt && echo PASS || echo FAIL'
  },

  // Chapter 10 — System Whisperer
  {
    id: 1037,
    chapter_id: 10,
    order_index: 1,
    slug: 'df-01',
    title: 'Disk Report',
    description: 'Save df -h output to /tmp/df.txt.',
    difficulty: 'B',
    tags: ['system', 'df'],
    xp_reward: 130,
    time_limit_seconds: 150,
    hints: ['Use df -h > /tmp/df.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/df.txt && grep -q "Filesystem" /tmp/df.txt && echo PASS || echo FAIL'
  },
  {
    id: 1038,
    chapter_id: 10,
    order_index: 2,
    slug: 'free-01',
    title: 'Memory Snapshot',
    description: 'Save free -h output to /tmp/free.txt.',
    difficulty: 'B',
    tags: ['system', 'memory'],
    xp_reward: 130,
    time_limit_seconds: 150,
    hints: ['Use free -h > /tmp/free.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/free.txt && grep -q "Mem" /tmp/free.txt && echo PASS || echo FAIL'
  },
  {
    id: 1039,
    chapter_id: 10,
    order_index: 3,
    slug: 'lscpu-01',
    title: 'CPU Intel',
    description: 'Save lscpu output to /tmp/lscpu.txt.',
    difficulty: 'B',
    tags: ['system', 'cpu'],
    xp_reward: 135,
    time_limit_seconds: 150,
    hints: ['Use lscpu > /tmp/lscpu.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/lscpu.txt && grep -q "CPU" /tmp/lscpu.txt && echo PASS || echo FAIL'
  },
  {
    id: 1040,
    chapter_id: 10,
    order_index: 4,
    slug: 'uptime-01',
    title: 'System Uptime',
    description: 'Save uptime output to /tmp/uptime.txt.',
    difficulty: 'B',
    tags: ['system', 'uptime'],
    xp_reward: 135,
    time_limit_seconds: 150,
    hints: ['Use uptime > /tmp/uptime.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/uptime.txt && grep -q "load average" /tmp/uptime.txt && echo PASS || echo FAIL'
  },

  // Chapter 11 — Shell Scribe
  {
    id: 1041,
    chapter_id: 11,
    order_index: 1,
    slug: 'script-01',
    title: 'First Script',
    description: 'Create /tmp/hello.sh with a shebang and echo "hello".',
    difficulty: 'B',
    tags: ['bash', 'script'],
    xp_reward: 150,
    time_limit_seconds: 180,
    hints: ['Add #!/bin/bash at top.', 'echo "hello" in script.'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/hello.sh && grep -q "^#!/bin/bash" /tmp/hello.sh && grep -q "echo" /tmp/hello.sh && echo PASS || echo FAIL'
  },
  {
    id: 1042,
    chapter_id: 11,
    order_index: 2,
    slug: 'vars-01',
    title: 'Script Args',
    description: 'Create /tmp/args.sh that echoes $1.',
    difficulty: 'B',
    tags: ['bash', 'script'],
    xp_reward: 150,
    time_limit_seconds: 180,
    hints: ['Use $1 in echo.', 'echo "$1"'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/args.sh && grep -q "\\$1" /tmp/args.sh && echo PASS || echo FAIL'
  },
  {
    id: 1043,
    chapter_id: 11,
    order_index: 3,
    slug: 'if-01',
    title: 'Conditional Logic',
    description: 'Create /tmp/check.sh that checks if /tmp/flag exists and echoes "ON".',
    difficulty: 'B',
    tags: ['bash', 'script'],
    xp_reward: 155,
    time_limit_seconds: 180,
    hints: ['Use if [ -f /tmp/flag ]', 'echo "ON" inside'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/check.sh && grep -q "if" /tmp/check.sh && grep -q "/tmp/flag" /tmp/check.sh && echo PASS || echo FAIL'
  },
  {
    id: 1044,
    chapter_id: 11,
    order_index: 4,
    slug: 'loop-01',
    title: 'Loop Master',
    description: 'Create /tmp/loop.sh with a for loop that echoes numbers.',
    difficulty: 'B',
    tags: ['bash', 'script'],
    xp_reward: 155,
    time_limit_seconds: 180,
    hints: ['Use for i in 1 2 3; do echo $i; done'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/loop.sh && grep -q "for" /tmp/loop.sh && echo PASS || echo FAIL'
  },

  // Chapter 12 — The Dungeon Master
  {
    id: 1045,
    chapter_id: 12,
    order_index: 1,
    slug: 'cron-01',
    title: 'Cron Entry',
    description: 'Write a daily midnight cron line into /tmp/cron.txt.',
    difficulty: 'A',
    tags: ['cron', 'automation'],
    xp_reward: 170,
    time_limit_seconds: 200,
    hints: ['Format: 0 0 * * *', 'echo "0 0 * * * /tmp/job.sh" > /tmp/cron.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/cron.txt && grep -q "^0 0 \\* \\* \\*" /tmp/cron.txt && echo PASS || echo FAIL'
  },
  {
    id: 1046,
    chapter_id: 12,
    order_index: 2,
    slug: 'at-01',
    title: 'Trap the Signal',
    description: 'Create /tmp/trap.sh with a trap for EXIT.',
    difficulty: 'A',
    tags: ['bash', 'script'],
    xp_reward: 170,
    time_limit_seconds: 200,
    hints: ['Use trap "..." EXIT'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/trap.sh && grep -q "trap" /tmp/trap.sh && grep -q "EXIT" /tmp/trap.sh && echo PASS || echo FAIL'
  },
  {
    id: 1047,
    chapter_id: 12,
    order_index: 3,
    slug: 'trap-01',
    title: 'Heredoc Message',
    description: 'Create /tmp/heredoc.txt with two lines: alpha and beta.',
    difficulty: 'A',
    tags: ['bash', 'heredoc'],
    xp_reward: 175,
    time_limit_seconds: 200,
    hints: ['Use cat <<EOF > /tmp/heredoc.txt'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/heredoc.txt && grep -qx "alpha" /tmp/heredoc.txt && grep -qx "beta" /tmp/heredoc.txt && echo PASS || echo FAIL'
  },
  {
    id: 1048,
    chapter_id: 12,
    order_index: 4,
    slug: 'heredoc-01',
    title: 'Regex Hunt',
    description: 'Use grep -E to extract lines starting with WARN into /tmp/warn.txt.',
    difficulty: 'A',
    tags: ['regex', 'grep'],
    xp_reward: 175,
    time_limit_seconds: 200,
    hints: ['Use grep -E "^WARN"'],
    setup_script: 'printf "INFO ok\nWARN disk\nWARN net\n" > /tmp/logs.txt',
    validator_script: 'test -f /tmp/warn.txt && grep -q "^WARN" /tmp/warn.txt && ! grep -q "^INFO" /tmp/warn.txt && echo PASS || echo FAIL'
  },

  // Chapter 13 — Shadow Admin
  {
    id: 1049,
    chapter_id: 13,
    order_index: 1,
    slug: 'useradd-01',
    title: 'New Hunter',
    description: 'Create a user named hunter.',
    difficulty: 'A',
    tags: ['users', 'security'],
    xp_reward: 190,
    time_limit_seconds: 220,
    hints: ['Use useradd hunter.'],
    setup_script: 'true',
    validator_script: 'getent passwd hunter >/dev/null 2>&1 && echo PASS || echo FAIL'
  },
  {
    id: 1050,
    chapter_id: 13,
    order_index: 2,
    slug: 'group-01',
    title: 'Create a Group',
    description: 'Create a group named hunters.',
    difficulty: 'A',
    tags: ['groups', 'security'],
    xp_reward: 190,
    time_limit_seconds: 220,
    hints: ['Use groupadd hunters.'],
    setup_script: 'true',
    validator_script: 'getent group hunters >/dev/null 2>&1 && echo PASS || echo FAIL'
  },
  {
    id: 1051,
    chapter_id: 13,
    order_index: 3,
    slug: 'sudo-01',
    title: 'Forge Keys',
    description: 'Generate an SSH key at /tmp/hunter_key (no passphrase).',
    difficulty: 'A',
    tags: ['security', 'ssh'],
    xp_reward: 195,
    time_limit_seconds: 220,
    hints: ['Use ssh-keygen -f /tmp/hunter_key -N ""'],
    setup_script: 'true',
    validator_script: 'test -f /tmp/hunter_key && test -f /tmp/hunter_key.pub && echo PASS || echo FAIL'
  },
  {
    id: 1052,
    chapter_id: 13,
    order_index: 4,
    slug: 'ssh-keygen-01',
    title: 'Encrypt the Scroll',
    description: 'Create /tmp/secret.gpg by symmetrically encrypting /tmp/secret.txt with password "hunter".',
    difficulty: 'A',
    tags: ['security', 'gpg'],
    xp_reward: 200,
    time_limit_seconds: 220,
    hints: ['Use gpg --symmetric --batch --passphrase hunter -o /tmp/secret.gpg /tmp/secret.txt'],
    setup_script: 'echo "treasure" > /tmp/secret.txt',
    validator_script: 'test -f /tmp/secret.gpg && echo PASS || echo FAIL'
  },

  // Chapter 14 — S-Rank Trial
  {
    id: 1053,
    chapter_id: 14,
    order_index: 1,
    slug: 'trial-rescue',
    title: 'Rescue the Server',
    description: 'Fix permissions on /tmp/trial/secure.txt to 600.',
    difficulty: 'S',
    tags: ['permissions', 'trial'],
    xp_reward: 240,
    time_limit_seconds: 240,
    hints: ['Use chmod 600 /tmp/trial/secure.txt'],
    setup_script: 'mkdir -p /tmp/trial && echo "core" > /tmp/trial/secure.txt && chmod 777 /tmp/trial/secure.txt',
    validator_script: 'perms=$(stat -c "%a" /tmp/trial/secure.txt); [ "$perms" = "600" ] && echo PASS || echo FAIL'
  },
  {
    id: 1054,
    chapter_id: 14,
    order_index: 2,
    slug: 'trial-logs',
    title: 'Log Forensics',
    description: 'Find lines containing "intruder" in /tmp/trial/auth.log and save to /tmp/trial/intruder.txt.',
    difficulty: 'S',
    tags: ['grep', 'trial'],
    xp_reward: 240,
    time_limit_seconds: 240,
    hints: ['Use grep "intruder"'],
    setup_script: 'printf "ok\nintruder: 1\nok\nintruder: 2\n" > /tmp/trial/auth.log',
    validator_script: 'test -f /tmp/trial/intruder.txt && grep -q "intruder" /tmp/trial/intruder.txt && echo PASS || echo FAIL'
  },
  {
    id: 1055,
    chapter_id: 14,
    order_index: 3,
    slug: 'trial-automation',
    title: 'Automate Cleanup',
    description: 'Write a script /tmp/trial/cleanup.sh that removes *.log in /tmp/trial/logs.',
    difficulty: 'S',
    tags: ['bash', 'trial'],
    xp_reward: 250,
    time_limit_seconds: 240,
    hints: ['Use rm /tmp/trial/logs/*.log inside script.'],
    setup_script: 'mkdir -p /tmp/trial/logs && touch /tmp/trial/logs/a.log /tmp/trial/logs/b.log',
    validator_script: 'test -f /tmp/trial/cleanup.sh && grep -q "rm" /tmp/trial/cleanup.sh && echo PASS || echo FAIL'
  },
  {
    id: 1056,
    chapter_id: 14,
    order_index: 4,
    slug: 'trial-pipeline',
    title: 'Pipeline Master',
    description: 'Use pipes to extract unique sorted entries from /tmp/trial/data.txt into /tmp/trial/out.txt.',
    difficulty: 'S',
    tags: ['pipes', 'trial'],
    xp_reward: 260,
    time_limit_seconds: 240,
    hints: ['Use sort | uniq.', 'cat /tmp/trial/data.txt | sort | uniq > /tmp/trial/out.txt'],
    setup_script: 'printf "beta\nalpha\nalpha\n" > /tmp/trial/data.txt',
    validator_script: 'test -f /tmp/trial/out.txt && head -n1 /tmp/trial/out.txt | grep -qx "alpha" && echo PASS || echo FAIL'
  }
];

export function getFallbackChallengeBySlug(slug: string) {
  const slugCandidates = getChallengeSlugCandidates(slug);
  for (const candidate of slugCandidates) {
    const match = fallbackChallenges.find((challenge) => challenge.slug === candidate);
    if (match) return match;
  }
  return null;
}

export function getFallbackChallengesByChapterId(chapterId: number) {
  return fallbackChallenges
    .filter((challenge) => challenge.chapter_id === chapterId)
    .sort((a, b) => a.order_index - b.order_index);
}
